# These are supported funding model platforms

github: [LukeMurphey]
custom: ['https://www.paypal.com/donate?business=MQSKTS3W7LUTY&item_name=Support+continued+development+of+Splunk+apps&currency_code=USD']
